name: 'Terraform Apply - Single Workspace'
description: 'Runs a terraform apply for a repo with a single workspace (i.e. soylent-green, discworld).'
inputs:
  ssh_key:
    description: '[secret] GitHub SSH Key for pulling repo.'
    required: true
  terraform_version:
    description: '[decimal] (i.e. 1.0.11) Terraform version to use.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      env:
        SSH_KEY: ${{ inputs.ssh_key }}
        TERRAFORM_VERSION: ${{ inputs.terraform_version }}
      run: |
        cd ${{ github.action_path }}
        source ../../shell-scripts/input-validator.sh
        
        declare -A inputs
        inputs[terraform_version]="$TERRAFORM_VERSION"
        inputs[ssh_key]="$SSH_KEY"
        
        validateInput inputs
      shell: bash
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh_key }}
    - name: Pull
      uses: actions/checkout@v3
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: TF Plan - Setup
      run: |
        terraform version
        terraform init -lock=true -lock-timeout=0s -input=false
        terraform validate
        terraform workspace show
      shell: bash
    - name: TF Plan - Run
      id: plan
      run: |
        terraform plan -lock=true -lock-timeout=0s -input=false -out=tfplan
      shell: bash
    - name: TF Plan - Show
      id: show_plan
      run: |
        terraform show tfplan
      shell: bash
    - name: TF Apply - Run
      run: |
        terraform apply -lock=true -lock-timeout=0s -input=false tfplan
      shell: bash
      
