name: 'Terraform Apply - Multiple Workspaces'
description: 'Runs a terraform apply for a repo with a multiple workspaces (i.e. most terminus repos).'
inputs:
  ssh_key:
    description: '[secret] GitHub SSH Key for pulling repo.'
    required: true
  terraform_version:
    description: '[decimal] (i.e. 1.0.11) Terraform version to use.'
    required: true
  terraform_workspace:
    description: '[string] (i.e. ninja/prod-east) TF Workspace.'
    required: true
  artifactory_enabled:
    description: '[bool] (i.e. true/false) Whether or not the repo uses artifactory for the helm chart.'
    default: 'false'
    required: false
  artifactory_read_access_token:
    description: '[secret] Read access token for artifactory.'
    required: false
  artifactory_helm_chart_path:
    description: '[string] Path to helm chart for artifactory.'
    required: false
  datadog_api_key:
    description: '[secret] DataDog API Key. Required for the git-metadata upload.'
    required: false
  dd_trigger_synthetic_tests:
    description: '[bool] (i.e. true/false) Enable the tf plan commenter.'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      env:
        SSH_KEY: ${{ inputs.ssh_key }}
        TERRAFORM_VERSION: ${{ inputs.terraform_version }}
        TERRAFORM_WORKSPACE: ${{ inputs.terraform_workspace }}
      run: |
        cd ${{ github.action_path }}
        source ../../shell-scripts/input-validator.sh

        declare -A inputs
        inputs[ssh_key]="$SSH_KEY"
        inputs[terraform_version]="$TERRAFORM_VERSION"
        inputs[terraform_workspace]="TERRAFORM_WORKSPACE"

        validateInput inputs
      shell: bash
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ inputs.ssh_key }}
    - name: Install Datadog CI
      run: |
        yarn global add @datadog/datadog-ci
      shell: bash
    - name: Pull
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.deployment.ref }}
        lfs: true
    - name: Upload Git MetaData to Datadog
      if: ${{ inputs.datadog_api_key != '' }}
      run: |
        export DATADOG_API_KEY=${{ inputs.datadog_api_key }}
        datadog-ci git-metadata upload
      shell: bash
    - name: Update deployment status (pending)
      if: always()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ github.token }}
        state: pending
        deployment-id: ${{ github.event.deployment.id }}
    - name: Helm Update
      if: ${{ inputs.artifactory_enabled == 'true' }}
      run: |
        helm repo add terminus https://getterminus.jfrog.io/artifactory/default-helm/ --username developer --password ${{ inputs.artifactory_read_access_token }}
        helm repo update
        find helm/charts -maxdepth 1 -not -path "helm/charts" | xargs -n 1 helm dependency update
      shell: bash
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: TF Apply
      run: |
        if [ ! -z ${{ inputs.datadog_api_key }} ]
        then
          echo "Setting DATADOG_API_KEY to ${{ inputs.datadog_api_key }} from inputs.datadog_api_key"
          export DATADOG_API_KEY=${{ inputs.datadog_api_key }}
        fi
        terraform version
        terraform init -lock=false -input=false
        terraform validate
        terraform workspace select ${{ inputs.terraform_workspace }}
        terraform workspace show
        terraform plan $(printf -- '-var-file=%s ' vars/${{ inputs.terraform_workspace }}*.tfvars) -lock=true -lock-timeout=0s -input=false -out=tfplan
        terraform apply -lock=true -lock-timeout=0s -input=false tfplan
      shell: bash
    - name: Set Github Repo to Env Variable
      run: |
        echo "GITHUB_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      shell: bash
    - name: Check Datadog Keys
      if: ${{ inputs.dd_trigger_synthetic_tests == 'true' }}
      id: dd_keys
      run: |
        if [ -z ${{ env.DATADOG_API_KEY }} ]
        then
          echo ""
          echo "::warning title=DATADOG_API_KEY Not Set::DATADOG_API_KEY env variable must be set in order to trigger datadog synthetic tests from the CI."
          echo "::set-output name=dd_keys::false"
          echo ""
        fi
        if [ -z ${{ env.DATADOG_APP_KEY }} ]
        then
          echo ""
          echo "::warning title=DATADOG_APP_KEY Not Set::DATADOG_APP_KEY env variable must be set in order to trigger datadog synthetic tests from the CI."
          echo "::set-output name=dd_keys::false"
          echo ""
        fi
      shell: bash
    - name: Run Datadog Synthetics tests
      if: ${{ steps.dd_keys.outputs.dd_keys != 'false' && inputs.dd_trigger_synthetic_tests == 'true' }}
      uses: DataDog/synthetics-ci-github-action@v0.2.2
      with:
        api_key: ${{ env.DATADOG_API_KEY }}
        app_key: ${{ env.DATADOG_APP_KEY }}
        test_search_query: 'tag:managedby:*${{ env.GITHUB_REPOSITORY }}*'
    - name: Run Post Deploy Integration Cypress Tests
      if: ${{ inputs.cypress_test_branch != '' && inputs.cypress_test_workflow != '' && inputs.cypress_test_repo != '' && inputs.cypress_test_token != '' && inputs.cypress_test_env != '' }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        ref: refs/heads/${{ inputs.cypress_test_branch }}
        workflow: ${{ inputs.cypress_test_workflow }}
        repo: GetTerminus/${{ inputs.cypress_test_repo }}
        token: ${{ inputs.cypress_test_token }}
        inputs: '{ "environment": "${{ inputs.cypress_test_env }}" }'
    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ github.token }}
        state: success
        deployment-id: ${{ github.event.deployment.id }}
    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ github.token }}
        state: failure
        deployment-id: ${{ github.event.deployment.id }}
