name: "Remove GHCR Image(s)"
description: "Destroys the docker image(s)"
inputs:
  min_versions_to_keep:
    description: "[int] Number of latest versions to keep"
    required: false
    default: "0"
  environment:
    description: "[string] Environment to push to (default, stage, prod)"
    required: true
  ghcr_image_version:
    description: "[string] GHCR image version"
    required: true
  service_name:
    description: "[string] Name of the service to remove images for"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "Remove ${{ inputs.ghcr_image_version }} GHCR Images from ${{ inputs.environment }}"
      uses: actions/delete-package-versions@v4
      with:
        package-version-ids: "${{ inputs.service_name }}-${{ inputs.ghcr_image_version }}"
        package-name: "${{ github.event.repository.name }}/${{ inputs.environment }}"
        package-type: "container"
        min-versions-to-keep: ${{ inputs.min_versions_to_keep }}
        delete-only-pre-release-versions: "false"

    - name: Clean up all untagged versions
      uses: actions/delete-package-versions@v4
      with:
        package-name: "${{ github.event.repository.name }}/${{ inputs.environment }}"
        package-type: "container"
        delete-only-untagged-versions: "true"
