name: "Get Dir Names"
description: "Gets a JSON list of dir names based on the directory"
inputs:
  directory:
    description: "[string] Directory that contains all of the services"
    required: true
outputs:
  service_names:
    description: "[jsonArray(string)] Json array of service names"
    value: ${{ steps.get-service-info.outputs.service_names }}
  process_names:
    description: "[jsonArray(string)] Json array of process names"
    value: ${{ steps.get-process-info.outputs.process_names }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get Service Info
      id: get-service-info
      working-directory: ${{ inputs.directory }}
      run: |
        source ${{ github.action_path }}/../../shell-scripts/service-utils.sh

        service_names=`getDirNames .`
        echo "service_names=$service_names" >> $GITHUB_OUTPUT
      shell: bash
    - name: Get Process Info
      id: get-process-info
      working-directory: ${{ inputs.directory }}
      env:
        service_names: ${{ steps.get-service-info.outputs.service_names }}
      run: |
        source ${{ github.action_path }}/../../shell-scripts/service-utils.sh

        for service in $(echo "$service_names" | jq -r '.[]'); do 
        process_name=$(getDirNames ./"$service"/dockerfiles)
        process_names=$(echo "$process_name $process_names" | jq -s "add")
        done
        echo "process_names=$process_names" >> $GITHUB_OUTPUT
      shell: bash
