name: "Get Dir Names"
description: "Gets a JSON list of dir names based on the directory"
inputs:
  directory:
    description: "[string] Directory that contains all of the services"
    required: true
outputs:
  names:
    description: "[jsonArray(string)] Json array of service names"
    value: ${{ steps.get-service-info.outputs.service_names }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get Service Info
      id: get-service-info
      working-directory: ${{ inputs.directory }}
      run: |
        source ${{ github.action_path }}/../../shell-scripts/service-utils.sh

        service_names=`getDirNames .`
        echo "service_names=$service_names" >> $GITHUB_OUTPUT
      shell: bash
