name: 'Terraform Plan - Multiple Workspaces'
description: 'Runs a terraform plan for a for a repo with a multiple workspaces (i.e. most terminus repos).'
inputs:
  ssh-private-key:
    description: 'Private key for ssh agent.'
    required: true
  terraform-version:
    description: 'Version of terraform to use.'
    required: true
  github-token:
    description: 'Github token for plan commenter to use.'
    required: true
  enable-plan-commenter:
    description: 'Enable the tf plan commenter.'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Pull
      uses: actions/checkout@v2
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ inputs.terraform-version }}
    - name: TF Plan - Setup
      run: |
        terraform version
        terraform init -lock=false -input=false
        terraform validate
        terraform workspace show
      shell: bash
    - name: TF Plan - Run
      id: plan
      run: |
        terraform plan -lock=false -input=false -out=tfplan
      shell: bash
    - name: TF Plan - show
      id: show_plan
      run: |
        terraform show tfplan
      shell: bash
    - name: Post Plan Comment
      if: always() && github.ref != ${{ github.event.repository.default_branch }} && ${{ inputs.enable-plan-commenter }} == 'true' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
      uses: robburger/terraform-pr-commenter@v1.5.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        EXPAND_SUMMARY_DETAILS: "false"
      with:
        commenter_type: plan
        commenter_input: ${{ format('{0}{1}', steps.show_plan.outputs.stdout, steps.plan.outputs.stderr) }}
        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
        