name: 'Terraform Apply - Single Environment'
description: 'Runs a terraform apply for a repo with a single workspace (i.e. soylent-green, discworld).'
inputs:
  ssh-private-key:
    description: 'Private key for ssh agent.'
    required: true
  terraform-version:
    description: 'Version of terraform to use.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Pull
      uses: actions/checkout@v2
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ inputs.terraform-version }}
    - name: TF Plan - Setup
      run: |
        terraform version
        terraform init -lock=true -lock-timeout=0s -input=false
        terraform validate
        terraform workspace show
      shell: bash
    - name: TF Plan - Run
      id: plan
      run: |
        terraform plan -lock=true -lock-timeout=0s -input=false -out=tfplan
      shell: bash
    - name: TF Plan - Show
      id: show_plan
      run: |
        terraform show tfplan
      shell: bash
    - name: TF Apply - Run
      run: |
        terraform apply -lock=true -lock-timeout=0s -input=false tfplan
      shell: bash
      