name: 'Identify Build Targets'
description: 'Identifies Build Targets'
inputs:
  ssh_key:
    description: '[secret] GitHub SSH Key for pulling repo.'
    required: true
outputs:
  matrix:
    description: '[obj] Matrix of Build Targets'
    value: ${{ steps.matrix.outputs.value }}
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      env:
        SSH_KEY: ${{ inputs.ssh_key }}
      run: |
        cd ${{ github.action_path }}
        source ../../shell-scripts/input-validator.sh

        declare -A inputs
        inputs[ssh_key]="$SSH_KEY"

        validateInput inputs

        declare -A envVariables
        envVariables[GOLANG_PROTOBUF_REGISTRATION_CONFLICT]=$GOLANG_PROTOBUF_REGISTRATION_CONFLICT
        envVariables[GOPROXY]=$GOPROXY
        envVariables[GONOSUMDB]=$GONOSUMDB

        validateInput envVariables
      shell: bash
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh_key }}
    - name: Pull
      uses: actions/checkout@v3
    - id: matrix
      uses: sergeysova/jq-action@v2
      with:
        cmd: echo "\"$(ls cmd | tr "\n" " ")\""  | jq -M -c 'split(" ")|map(select(length > 0))'
