name: 'Terraform Deploy EKS - Single Workspace'
description: 'Triggers a workflow dispatch of EKS Infra - Terraform Apply.'
inputs:
  pull_access_token:
    description: '[secret] Github pull access token.'
    required: true
runs:
  using: "composite"
  steps:
  - name: Deploy EKS Infra
    uses: benc-uk/workflow-dispatch@v1
    with:
      workflow: Terraform Apply
      token: ${{ inputs.pull_access_token }}
      repo: GetTerminus/eks-infra
      ref: master
      inputs: '{"environment": "all"}'
      