name: 'Terraform Deploy EKS - Single Workspace'
description: 'Triggers a workflow dispatch of EKS Infra - Terraform Apply.'
inputs:
  gh_deployment_access_token:
    description: '[secret] GitHub deployment access token.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      env:
        GH_DEPLOYMENT_ACCESS_TOKEN: ${{ inputs.gh_deployment_access_token }}
      run: |
        cd ${{ github.action_path }}
        source ../../shell-scripts/input-validator.sh

        declare -A inputs
        inputs[gh_deployment_access_token]="$GH_DEPLOYMENT_ACCESS_TOKEN"

        validateInput inputs
      shell: bash
    - name: Create EKS Deployment
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ inputs.gh_deployment_access_token }}" \
        https://api.github.com/repos/GetTerminus/eks-infra/deployments \
        -d '{"ref":"master","environment":"all"}'
      shell: bash
